spring:
  datasource:
    url: jdbc:mariadb://localhost:${testDbIp}:3306/app1_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${testDbUsername:root}
    password: ${testDbPassword:}
  jpa:
    hibernate:
      ddl-auto: create
